version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-punchtracker}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ../backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-punchtracker}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-key-here}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - JWT_EXPIRE_MINUTES=${JWT_EXPIRE_MINUTES:-1440}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY:-your-sendgrid-api-key-here}
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-your-email@gmail.com}
      - SMTP_PASS=${SMTP_PASS:-your-app-password}
      - REPORT_SCHEDULE_CRON=${REPORT_SCHEDULE_CRON:-0 8 * * MON}
      - SLACK_WEBHOOK_DEFAULT=${SLACK_WEBHOOK_DEFAULT:-https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK}
      - DISCORD_WEBHOOK_DEFAULT=${DISCORD_WEBHOOK_DEFAULT:-https://discord.com/api/webhooks/YOUR/DISCORD/WEBHOOK}
      - EMAIL_VERIFY_TOKEN_TTL_MIN=${EMAIL_VERIFY_TOKEN_TTL_MIN:-60}
      - PASSWORD_RESET_TOKEN_TTL_MIN=${PASSWORD_RESET_TOKEN_TTL_MIN:-60}
      - WEBHOOK_HMAC_HEADER=${WEBHOOK_HMAC_HEADER:-X-Signature}
      - WEBHOOK_DRIFT_SEC=${WEBHOOK_DRIFT_SEC:-120}
      - RATE_LIMIT_PER_MIN=${RATE_LIMIT_PER_MIN:-60}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - INACTIVITY_MINUTES=${INACTIVITY_MINUTES:-3}
      - SEGMENT_ACTIVE_MIN_S=${SEGMENT_ACTIVE_MIN_S:-40}
      - SEGMENT_REST_MIN_S=${SEGMENT_REST_MIN_S:-15}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: npm start

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3001"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_SERVER_HTTP_PORT=3001
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
